insert into ajvieira_isurvey_app.participante
(
	id_participante,
        nombre_participante,
        apellido_participante,
        email_participante,
        empresa,
        cargo,
        supervisor,
        fecha_nacimiento,
        fecha_ingreso,
        sexo,
        tipo_nomina,
        funcion,
        id_empresa
)
values
(
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        (select id_empresa from ajvieira_isurvey_security.s_user where userlogin = '${def:user}')
)
