INSERT INTO ajvieira_isurvey_app.participante
(
	id_participante,
	nombre_participante,
	apellido_participante,
	email_participante,
	telefono,
	empresa,
	sector_empresa,
	cargo,
	area,
	sexo,
	id_empresa,
	fecha_registro,
	verificado,
	id_estudio_identificado
)
values
(
	'{{id_participante}}',
	'{{nombre_participante}}',
	'{{apellido_participante}}',
	'{{email_participante}}',
	'{{telefono}}',
	'{{empresa}}',
	'{{sector_empresa}}',
	'{{cargo}}',
	'',
	'',
	'{{id_empresa}}',
	now(),
	'No',
	'{{id_estudio_identificado}}'
)
