INSERT INTO ajvieira_isurvey_app.participante
(
	id_participante,
	nombre_participante,
	apellido_participante,
	email_participante,
	empresa,
	cargo,
	id_empresa,
	fecha_registro,
	verificado,
	fecha_verificacion
)
values
(
	'{{id_participante}}',
	'{{nombre_participante}}',
	'{{apellido_participante}}',
	'{{email_participante}}',
	'{{empresa}}',
	'{{cargo}}',
	'{{id_empresa}}',
	now(),
	'No',
	0000-00-00
)
